name: Discord Message Notify

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Message Notify
      uses: appleboy/discord-action@0.0.3
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#4BB4FF"
        username: "GitHub Bot"
        message: "**Title:** ${{ github.event.issue.title}}\n**Description:** ${{ github.event.issue.body}}\n**Labels:** ${{ github.event.issue.labels.*.name}}\n**URL:** ${{ github.event.issue.html_url}}"
