name: Discord Message Notify

on:
  pull_request:
    branches: [ develop ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Message Notify
      uses: appleboy/discord-action@0.0.3
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#48f442"
        username: "GitHub Bot"
        message: "**Title:** ${{ github.event.pull_request.title }}\n**Description:** ${{ github.event.pull_request.body }}\n**URL:** ${{ github.event.pull_request.html_url }}"
