name: Discord Push Notification

on:
  push:
    branches: [ develop ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification on Push to Develop
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "GitHub Bot"
          message: |
            **Pushed to develop branch**
            **Committer:** ${{ github.actor }}
            **Commit:** ${{ github.event.head_commit.message }}
            **URL:** ${{ github.event.repository.html_url }}/commit/${{ github.sha }}
